const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Behaviors.solid,
		C3.Behaviors.custom,
		C3.Behaviors.LOS,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Fade: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Pin: 0},
	{LiveFont3: 0},
	{LiveFont4: 0},
	{Sprite14: 0},
	{LiveFont5: 0},
	{shot1: 0},
	{shot2: 0},
	{shot3: 0},
	{shot4: 0},
	{shot5: 0},
	{Sprite24: 0},
	{LiveFont6: 0},
	{Sprite25: 0},
	{LiveFont7: 0},
	{Sprite26: 0},
	{Touch: 0},
	{Bullet: 0},
	{PinKnife: 0},
	{Particles: 0},
	{Rotate: 0},
	{Rueda: 0},
	{shot13: 0},
	{shot14: 0},
	{shot15: 0},
	{piece1: 0},
	{piece4: 0},
	{piece5: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{rayo: 0},
	{piece2: 0},
	{piece6: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{restart: 0},
	{Sprite27: 0},
	{fontmoney1: 0},
	{LiveFont9: 0},
	{LiteTween: 0},
	{Sprite19: 0},
	{ruedas: 0},
	{Sprite21: 0},
	{Audio: 0},
	{Sprite22: 0},
	{Particles2: 0},
	{Browser: 0},
	{home: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{selector1: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{RotateScreen: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Particles5: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite70: 0},
	{Particles6: 0},
	{Sprite72: 0},
	{Keyboard: 0},
	{Sprite73: 0},
	{Particles7: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{Giro: 0},
	{type: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{LiveFont10: 0},
	{p1: 0},
	{p2: 0},
	{p3: 0},
	{p4: 0},
	{p5: 0},
	{p6: 0},
	{p7: 0},
	{Sprite78: 0},
	{LiveFont11: 0},
	{Sprite7: 0},
	{Sprite23: 0},
	{Sprite79: 0},
	{s38: 0},
	{s39: 0},
	{s40: 0},
	{s41: 0},
	{s43: 0},
	{s46: 0},
	{s49: 0},
	{s52: 0},
	{s55: 0},
	{s61: 0},
	{s62: 0},
	{s63: 0},
	{s64: 0},
	{s66: 0},
	{s67: 0},
	{s69: 0},
	{s70: 0},
	{s71: 0},
	{s72: 0},
	{restart2: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{s73: 0},
	{s74: 0},
	{s75: 0},
	{Sprite87: 0},
	{Physics: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{pinner: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{Particles8: 0},
	{Particles9: 0},
	{Particles10: 0},
	{Particles11: 0},
	{Particles12: 0},
	{Particles13: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{LiveFont12: 0},
	{LiveFont13: 0},
	{Sprite99: 0},
	{ScrollTo: 0},
	{Sprite88: 0},
	{Sprite100: 0},
	{Sprite101: 0},
	{Sprite102: 0},
	{Sprite103: 0},
	{Sprite104: 0},
	{carte1: 0},
	{carte4: 0},
	{carte5: 0},
	{carte3: 0},
	{carte2: 0},
	{Sprite91: 0},
	{Sprite113: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Sprite116: 0},
	{Sprite117: 0},
	{LiveFont14: 0},
	{LiveFont15: 0},
	{Sprite118: 0},
	{Sprite119: 0},
	{Sprite120: 0},
	{Sprite121: 0},
	{Sprite122: 0},
	{Sprite123: 0},
	{Sprite124: 0},
	{Sprite127: 0},
	{Sprite128: 0},
	{Sprite132: 0},
	{Sprite136: 0},
	{LiveFont16: 0},
	{Sprite137: 0},
	{soundsprite: 0},
	{walksprite: 0},
	{Sine2: 0},
	{Sprite138: 0},
	{Sprite139: 0},
	{Particles14: 0},
	{Particles15: 0},
	{p8: 0},
	{p9: 0},
	{p10: 0},
	{p11: 0},
	{p12: 0},
	{p13: 0},
	{RESET: 0},
	{YES: 0},
	{NO: 0},
	{Sprite: 0},
	{brazo: 0},
	{laser: 0},
	{mira: 0},
	{DestroyOutsideLayout: 0},
	{Bullet2: 0},
	{Solid: 0},
	{Sprite20: 0},
	{Particles16: 0},
	{Particles17: 0},
	{tipo: 0},
	{torso: 0},
	{piernas: 0},
	{enemgo1: 0},
	{e: 0},
	{e2: 0},
	{Sprite69: 0},
	{Sprite71: 0},
	{Sprite82: 0},
	{Sprite83: 0},
	{sangre3: 0},
	{sangre1: 0},
	{sangre2: 0},
	{Sprite2: 0},
	{Sprite84: 0},
	{fonder: 0},
	{estrellaswins: 0},
	{continue: 0},
	{cancel: 0},
	{restarted: 0},
	{freemoney: 0},
	{fonder2: 0},
	{continue2: 0},
	{estrellaswins2: 0},
	{cancel2: 0},
	{restarted2: 0},
	{Sprite85: 0},
	{Sprite86: 0},
	{Sprite110: 0},
	{Sprite111: 0},
	{Sprite112: 0},
	{Particles18: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{Sprite129: 0},
	{redbullet: 0},
	{Sprite130: 0},
	{Sprite131: 0},
	{Sprite133: 0},
	{Sprite134: 0},
	{Sprite135: 0},
	{Sprite140: 0},
	{ex4: 0},
	{Sprite141: 0},
	{enemgo2: 0},
	{Sprite142: 0},
	{Sprite143: 0},
	{Sprite144: 0},
	{Sprite145: 0},
	{enemgo3: 0},
	{enemgo4: 0},
	{e3: 0},
	{e4: 0},
	{Sprite146: 0},
	{ex5: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Sprite149: 0},
	{Sprite150: 0},
	{Sprite151: 0},
	{Sprite152: 0},
	{Sprite153: 0},
	{Sprite154: 0},
	{Sprite155: 0},
	{Sprite156: 0},
	{Sprite157: 0},
	{Sprite158: 0},
	{Sprite159: 0},
	{Sprite161: 0},
	{Sprite162: 0},
	{LiveFont17: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{s5: 0},
	{s6: 0},
	{s7: 0},
	{s8: 0},
	{s9: 0},
	{s10: 0},
	{s11: 0},
	{s12: 0},
	{s13: 0},
	{s14: 0},
	{s15: 0},
	{s16: 0},
	{s17: 0},
	{s18: 0},
	{s19: 0},
	{s20: 0},
	{Sprite163: 0},
	{Sprite165: 0},
	{Sprite166: 0},
	{Sprite167: 0},
	{Sprite168: 0},
	{Sprite169: 0},
	{Sprite173: 0},
	{Sprite174: 0},
	{Sprite176: 0},
	{Sprite177: 0},
	{Sprite179: 0},
	{enemgo5: 0},
	{Sprite180: 0},
	{enemigo2: 0},
	{Sprite181: 0},
	{Sprite182: 0},
	{Sprite183: 0},
	{Sprite184: 0},
	{Sprite185: 0},
	{Sprite186: 0},
	{Sprite187: 0},
	{Sprite188: 0},
	{Sprite189: 0},
	{Sprite190: 0},
	{Sprite191: 0},
	{Sprite192: 0},
	{Sprite193: 0},
	{Sprite194: 0},
	{e5: 0},
	{e6: 0},
	{Sprite195: 0},
	{Sprite196: 0},
	{Sprite197: 0},
	{Sprite198: 0},
	{enemgo6: 0},
	{Sprite199: 0},
	{Sprite200: 0},
	{Sprite201: 0},
	{Sprite202: 0},
	{Sprite203: 0},
	{Sprite204: 0},
	{Sprite205: 0},
	{Sprite206: 0},
	{Sprite207: 0},
	{Sprite208: 0},
	{Sprite209: 0},
	{Sprite210: 0},
	{Sprite211: 0},
	{Sprite212: 0},
	{Sprite213: 0},
	{Sprite214: 0},
	{Sprite215: 0},
	{Sprite216: 0},
	{Sprite217: 0},
	{Sprite218: 0},
	{Sprite219: 0},
	{Sprite220: 0},
	{Sprite221: 0},
	{Sprite222: 0},
	{Sprite223: 0},
	{Sprite224: 0},
	{Sprite225: 0},
	{Sprite226: 0},
	{Sprite227: 0},
	{Sprite228: 0},
	{freemoney2: 0},
	{Sprite229: 0},
	{Sprite230: 0},
	{moneyhud1: 0},
	{moneyhud2: 0},
	{fontmoney2: 0},
	{Sprite231: 0},
	{CHECK: 0},
	{tipo4: 0},
	{tipo5: 0},
	{tipo6: 0},
	{tipo7: 0},
	{arma2: 0},
	{Sprite232: 0},
	{Sprite233: 0},
	{paster: 0},
	{Sprite234: 0},
	{Sprite235: 0},
	{bulletcouns: 0},
	{lampara: 0},
	{Sprite237: 0},
	{Sprite238: 0},
	{Sprite239: 0},
	{Sprite240: 0},
	{Sprite236: 0},
	{Sprite241: 0},
	{Sprite242: 0},
	{Sprite243: 0},
	{Sprite244: 0},
	{arma3: 0},
	{grena: 0},
	{POWER1: 0},
	{POWER2: 0},
	{Sprite245: 0},
	{Sprite246: 0},
	{Sprite247: 0},
	{Sprite248: 0},
	{Sprite249: 0},
	{arma4: 0},
	{grena2: 0},
	{Bullet3: 0},
	{Sprite250: 0},
	{Sprite251: 0},
	{Sprite252: 0},
	{Sprite253: 0},
	{guns: 0},
	{Sprite105: 0},
	{Sprite106: 0},
	{Sprite107: 0},
	{Sprite108: 0},
	{Sprite109: 0},
	{Sprite254: 0},
	{Sprite255: 0},
	{Sprite256: 0},
	{Sprite257: 0},
	{Sprite258: 0},
	{Sprite259: 0},
	{Sprite260: 0},
	{Sprite261: 0},
	{Sprite262: 0},
	{Sprite263: 0},
	{Sprite264: 0},
	{Sprite265: 0},
	{skinbutt: 0},
	{gunbutt: 0},
	{Sprite268: 0},
	{Sprite269: 0},
	{Sprite270: 0},
	{Sprite271: 0},
	{bulletcouns2: 0},
	{Sprite272: 0},
	{guns2: 0},
	{activated: 0},
	{CustomMovement: 0},
	{LineOfSight: 0},
	{cajaiman: 0},
	{cajaiman2: 0},
	{Sprite273: 0},
	{Sprite274: 0},
	{Sprite275: 0},
	{Sprite276: 0},
	{Sprite277: 0},
	{Sprite278: 0},
	{Sprite279: 0},
	{Sprite280: 0},
	{Sprite281: 0},
	{Sprite282: 0},
	{Sprite283: 0},
	{Sprite284: 0},
	{Sprite285: 0},
	{Sprite286: 0},
	{Sprite287: 0},
	{bulletcouns3: 0},
	{Sprite288: 0},
	{selector2: 0},
	{selector3: 0},
	{guns3: 0},
	{Sprite289: 0},
	{TIMECOUNT: 0},
	{enemgo7: 0},
	{enemgo8: 0},
	{Sprite290: 0},
	{laser2: 0},
	{brazo2: 0},
	{fonder3: 0},
	{Sprite267: 0},
	{Sprite292: 0},
	{Sprite293: 0},
	{Sprite294: 0},
	{Sprite295: 0},
	{Sprite296: 0},
	{Sprite297: 0},
	{Sprite298: 0},
	{Sprite299: 0},
	{Sprite300: 0},
	{Sprite301: 0},
	{Sprite302: 0},
	{Sprite303: 0},
	{Sprite304: 0},
	{Sprite305: 0},
	{Sprite306: 0},
	{Sprite307: 0},
	{Sprite308: 0},
	{Sprite309: 0},
	{Sprite310: 0},
	{Sprite311: 0},
	{Sprite312: 0},
	{Sprite313: 0},
	{Particles19: 0},
	{bulletcouns4: 0},
	{bulletcouns5: 0},
	{Sprite314: 0},
	{Sprite315: 0},
	{Sprite316: 0},
	{Sprite317: 0},
	{Sprite318: 0},
	{Sprite319: 0},
	{Sprite320: 0},
	{persona: 0},
	{e7: 0},
	{Sprite321: 0},
	{Sprite322: 0},
	{Sprite323: 0},
	{Sprite324: 0},
	{Sprite325: 0},
	{Sprite326: 0},
	{Sprite327: 0},
	{Sprite328: 0},
	{Sprite329: 0},
	{Sprite330: 0},
	{Sprite331: 0},
	{Sprite332: 0},
	{Sprite333: 0},
	{Sprite334: 0},
	{LiveFont8: 0},
	{Sprite335: 0},
	{Sprite336: 0},
	{Sprite337: 0},
	{Sprite338: 0},
	{Sprite339: 0},
	{Sprite340: 0},
	{Sprite341: 0},
	{Sprite342: 0},
	{Sprite343: 0},
	{s21: 0},
	{s22: 0},
	{s23: 0},
	{s24: 0},
	{Sprite344: 0},
	{Sprite345: 0},
	{Sprite346: 0},
	{Sprite347: 0},
	{Sprite348: 0},
	{Sprite349: 0},
	{s25: 0},
	{s26: 0},
	{s27: 0},
	{s28: 0},
	{s29: 0},
	{s30: 0},
	{Sprite350: 0},
	{Sprite351: 0},
	{Sprite352: 0},
	{Sprite353: 0},
	{Sprite354: 0},
	{Sprite355: 0},
	{Sprite356: 0},
	{Sprite357: 0},
	{Sprite358: 0},
	{Sprite359: 0},
	{Sprite360: 0},
	{Sprite361: 0},
	{Sprite362: 0},
	{Sprite363: 0},
	{Sprite364: 0},
	{Sprite365: 0},
	{Sprite366: 0},
	{Sprite367: 0},
	{Sprite368: 0},
	{Sprite369: 0},
	{Sprite370: 0},
	{Sprite371: 0},
	{Sprite372: 0},
	{Sprite373: 0},
	{Sprite374: 0},
	{Sprite375: 0},
	{Sprite376: 0},
	{Sprite377: 0},
	{flame1: 0},
	{Sprite378: 0},
	{Sprite379: 0},
	{Sprite380: 0},
	{Sprite381: 0},
	{bulletcouns6: 0},
	{Sprite382: 0},
	{ac5: 0},
	{ac2: 0},
	{ac3: 0},
	{ac4: 0},
	{ac6: 0},
	{ac1: 0},
	{flasher: 0},
	{Woods: 0},
	{Sprite383: 0},
	{Sprite384: 0},
	{Sprite385: 0},
	{brazo3: 0},
	{LocalStorage: 0},
	{Family4: 0},
	{Family1: 0},
	{Family2: 0},
	{Family3: 0},
	{bulletcajas: 0},
	{achieve16: 0},
	{achieve15: 0},
	{achieve14: 0},
	{achieve13: 0},
	{achieve12: 0},
	{achieve11: 0},
	{achieve10: 0},
	{achieve9: 0},
	{achieve8: 0},
	{achieve7: 0},
	{achieve6: 0},
	{achieve5: 0},
	{achieve4: 0},
	{achieve3: 0},
	{achieve2: 0},
	{achieve1: 0},
	{IsScreenRotate: 0},
	{sonido: 0},
	{Totalscore: 0},
	{mouseforce: 0},
	{losecount: 0},
	{toucher: 0},
	{Levelunlocker4: 0},
	{Levelunlocker3: 0},
	{Levelunlocker2: 0},
	{Levelunlocker: 0},
	{Bulletcount: 0},
	{maxbullets: 0},
	{failed: 0},
	{weaponselected: 0},
	{endlevel: 0},
	{damage: 0},
	{maxvida: 0},
	{levelnumber: 0},
	{vidaleft: 0},
	{Bulletsleft: 0},
	{shoot: 0},
	{guntype: 0},
	{speedupgrade: 0},
	{Score: 0},
	{colortype: 0},
	{adss: 0},
	{Combo: 0},
	{ads: 0},
	{complete: 0},
	{weapon16: 0},
	{weapon15: 0},
	{weapon14: 0},
	{weapon13: 0},
	{weapon12: 0},
	{weapon11: 0},
	{weapon10: 0},
	{weapon9: 0},
	{weapon8: 0},
	{weapon7: 0},
	{weapon6: 0},
	{weapon5: 0},
	{weapon4: 0},
	{weapon3: 0},
	{weapon2: 0},
	{BestScore: 0},
	{Beststage: 0},
	{gifttime: 0},
	{gifts: 0},
	{gameover: 0},
	{Skins: 0},
	{Leveltype: 0},
	{endstars: 0},
	{globalStars: 0},
	{level20star2: 0},
	{level20star: 0},
	{level21star: 0},
	{level22star: 0},
	{level23star: 0},
	{level24star: 0},
	{level25star: 0},
	{level19star: 0},
	{level18star: 0},
	{level17star: 0},
	{level16star: 0},
	{level15star: 0},
	{level14star: 0},
	{level13star: 0},
	{level12star: 0},
	{level11star: 0},
	{level10star: 0},
	{level9star: 0},
	{level8star: 0},
	{level7star: 0},
	{level6star: 0},
	{level5star: 0},
	{level4star: 0},
	{level3star: 0},
	{level2star: 0},
	{level1star: 0},
	{shots: 0},
	{Fuits: 0},
	{Stage: 0},
	{ShotsLeft: 0},
	{Highscore: 0},
	{level50star: 0},
	{level49star: 0},
	{level48star: 0},
	{level47star: 0},
	{level46star: 0},
	{level45star: 0},
	{level44star: 0},
	{level43star: 0},
	{level42star: 0},
	{level41star: 0},
	{level40star: 0},
	{level39star: 0},
	{level38star: 0},
	{level37star: 0},
	{level36star: 0},
	{level35star: 0},
	{level34star: 0},
	{level33star: 0},
	{level32star: 0},
	{level31star: 0},
	{level30star: 0},
	{level29star: 0},
	{level28star: 0},
	{level27star: 0},
	{level26star: 0},
	{addbullets: 0},
	{adddamage: 0},
	{bulletsprice: 0},
	{damageprice: 0},
	{buybullets: 0},
	{buydamage: 0},
	{money2: 0},
	{boots: 0},
	{randomunlock: 0},
	{timecount: 0},
	{canshooter: 0}
];

self.InstanceType = {
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	LiveFont3: class extends self.ISpriteFontInstance {},
	LiveFont4: class extends self.ISpriteFontInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	LiveFont5: class extends self.ISpriteFontInstance {},
	shot1: class extends self.ISpriteInstance {},
	shot2: class extends self.ISpriteInstance {},
	shot3: class extends self.ISpriteInstance {},
	shot4: class extends self.ISpriteInstance {},
	shot5: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	LiveFont6: class extends self.ISpriteFontInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	LiveFont7: class extends self.ISpriteFontInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	PinKnife: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Rueda: class extends self.ISpriteInstance {},
	shot13: class extends self.ISpriteInstance {},
	shot14: class extends self.ISpriteInstance {},
	shot15: class extends self.ISpriteInstance {},
	piece1: class extends self.ISpriteInstance {},
	piece4: class extends self.ISpriteInstance {},
	piece5: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	rayo: class extends self.ISpriteInstance {},
	piece2: class extends self.ISpriteInstance {},
	piece6: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	fontmoney1: class extends self.ISpriteFontInstance {},
	LiveFont9: class extends self.ISpriteFontInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	ruedas: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Browser: class extends self.IInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	selector1: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Particles7: class extends self.IParticlesInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	LiveFont10: class extends self.ISpriteFontInstance {},
	p1: class extends self.IParticlesInstance {},
	p2: class extends self.IParticlesInstance {},
	p3: class extends self.IParticlesInstance {},
	p4: class extends self.IParticlesInstance {},
	p5: class extends self.IParticlesInstance {},
	p6: class extends self.IParticlesInstance {},
	p7: class extends self.IParticlesInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	LiveFont11: class extends self.ISpriteFontInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	s38: class extends self.ISpriteInstance {},
	s39: class extends self.ISpriteInstance {},
	s40: class extends self.ISpriteInstance {},
	s41: class extends self.ISpriteInstance {},
	s43: class extends self.ISpriteInstance {},
	s46: class extends self.ISpriteInstance {},
	s49: class extends self.ISpriteInstance {},
	s52: class extends self.ISpriteInstance {},
	s55: class extends self.ISpriteInstance {},
	s61: class extends self.ISpriteInstance {},
	s62: class extends self.ISpriteInstance {},
	s63: class extends self.ISpriteInstance {},
	s64: class extends self.ISpriteInstance {},
	s66: class extends self.ISpriteInstance {},
	s67: class extends self.ISpriteInstance {},
	s69: class extends self.ISpriteInstance {},
	s70: class extends self.ISpriteInstance {},
	s71: class extends self.ISpriteInstance {},
	s72: class extends self.ISpriteInstance {},
	restart2: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	s73: class extends self.ISpriteInstance {},
	s74: class extends self.ISpriteInstance {},
	s75: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	pinner: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Particles8: class extends self.IParticlesInstance {},
	Particles9: class extends self.IParticlesInstance {},
	Particles10: class extends self.IParticlesInstance {},
	Particles11: class extends self.IParticlesInstance {},
	Particles12: class extends self.IParticlesInstance {},
	Particles13: class extends self.IParticlesInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	LiveFont12: class extends self.ISpriteFontInstance {},
	LiveFont13: class extends self.ISpriteFontInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	carte1: class extends self.ISpriteInstance {},
	carte4: class extends self.ISpriteInstance {},
	carte5: class extends self.ISpriteInstance {},
	carte3: class extends self.ISpriteInstance {},
	carte2: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite113: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	LiveFont14: class extends self.ISpriteFontInstance {},
	LiveFont15: class extends self.ISpriteFontInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	Sprite124: class extends self.ISpriteInstance {},
	Sprite127: class extends self.ISpriteInstance {},
	Sprite128: class extends self.ISpriteInstance {},
	Sprite132: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	LiveFont16: class extends self.ISpriteFontInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	soundsprite: class extends self.ISpriteInstance {},
	walksprite: class extends self.ISpriteInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	Particles14: class extends self.IParticlesInstance {},
	Particles15: class extends self.IParticlesInstance {},
	p8: class extends self.IParticlesInstance {},
	p9: class extends self.IParticlesInstance {},
	p10: class extends self.IParticlesInstance {},
	p11: class extends self.IParticlesInstance {},
	p12: class extends self.IParticlesInstance {},
	p13: class extends self.IParticlesInstance {},
	RESET: class extends self.ISpriteInstance {},
	YES: class extends self.ISpriteInstance {},
	NO: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	brazo: class extends self.ISpriteInstance {},
	laser: class extends self.ISpriteInstance {},
	mira: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Bullet2: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Particles16: class extends self.IParticlesInstance {},
	Particles17: class extends self.IParticlesInstance {},
	tipo: class extends self.ISpriteInstance {},
	torso: class extends self.ISpriteInstance {},
	piernas: class extends self.ISpriteInstance {},
	enemgo1: class extends self.ISpriteInstance {},
	e: class extends self.ISpriteInstance {},
	e2: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	sangre3: class extends self.ISpriteInstance {},
	sangre1: class extends self.ISpriteInstance {},
	sangre2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	fonder: class extends self.ISpriteInstance {},
	estrellaswins: class extends self.ISpriteInstance {},
	continue: class extends self.ISpriteInstance {},
	cancel: class extends self.ISpriteInstance {},
	restarted: class extends self.ISpriteInstance {},
	freemoney: class extends self.ISpriteInstance {},
	fonder2: class extends self.ISpriteInstance {},
	continue2: class extends self.ISpriteInstance {},
	estrellaswins2: class extends self.ISpriteInstance {},
	cancel2: class extends self.ISpriteInstance {},
	restarted2: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Sprite112: class extends self.ISpriteInstance {},
	Particles18: class extends self.IParticlesInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	redbullet: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite131: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	ex4: class extends self.ISpriteInstance {},
	Sprite141: class extends self.ISpriteInstance {},
	enemgo2: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	enemgo3: class extends self.ISpriteInstance {},
	enemgo4: class extends self.ISpriteInstance {},
	e3: class extends self.ISpriteInstance {},
	e4: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	ex5: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	Sprite153: class extends self.ISpriteInstance {},
	Sprite154: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Sprite157: class extends self.ISpriteInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	LiveFont17: class extends self.ISpriteFontInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	s6: class extends self.ISpriteInstance {},
	s7: class extends self.ISpriteInstance {},
	s8: class extends self.ISpriteInstance {},
	s9: class extends self.ISpriteInstance {},
	s10: class extends self.ISpriteInstance {},
	s11: class extends self.ISpriteInstance {},
	s12: class extends self.ISpriteInstance {},
	s13: class extends self.ISpriteInstance {},
	s14: class extends self.ISpriteInstance {},
	s15: class extends self.ISpriteInstance {},
	s16: class extends self.ISpriteInstance {},
	s17: class extends self.ISpriteInstance {},
	s18: class extends self.ISpriteInstance {},
	s19: class extends self.ISpriteInstance {},
	s20: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	Sprite168: class extends self.ISpriteInstance {},
	Sprite169: class extends self.ISpriteInstance {},
	Sprite173: class extends self.ISpriteInstance {},
	Sprite174: class extends self.ISpriteInstance {},
	Sprite176: class extends self.ISpriteInstance {},
	Sprite177: class extends self.ISpriteInstance {},
	Sprite179: class extends self.ISpriteInstance {},
	enemgo5: class extends self.ISpriteInstance {},
	Sprite180: class extends self.ISpriteInstance {},
	enemigo2: class extends self.ISpriteInstance {},
	Sprite181: class extends self.ISpriteInstance {},
	Sprite182: class extends self.ISpriteInstance {},
	Sprite183: class extends self.ISpriteInstance {},
	Sprite184: class extends self.ISpriteInstance {},
	Sprite185: class extends self.ISpriteInstance {},
	Sprite186: class extends self.ISpriteInstance {},
	Sprite187: class extends self.ISpriteInstance {},
	Sprite188: class extends self.ISpriteInstance {},
	Sprite189: class extends self.ISpriteInstance {},
	Sprite190: class extends self.ISpriteInstance {},
	Sprite191: class extends self.ISpriteInstance {},
	Sprite192: class extends self.ISpriteInstance {},
	Sprite193: class extends self.ISpriteInstance {},
	Sprite194: class extends self.ISpriteInstance {},
	e5: class extends self.ISpriteInstance {},
	e6: class extends self.ISpriteInstance {},
	Sprite195: class extends self.ISpriteInstance {},
	Sprite196: class extends self.ISpriteInstance {},
	Sprite197: class extends self.ISpriteInstance {},
	Sprite198: class extends self.ISpriteInstance {},
	enemgo6: class extends self.ISpriteInstance {},
	Sprite199: class extends self.ISpriteInstance {},
	Sprite200: class extends self.ISpriteInstance {},
	Sprite201: class extends self.ISpriteInstance {},
	Sprite202: class extends self.ISpriteInstance {},
	Sprite203: class extends self.ISpriteInstance {},
	Sprite204: class extends self.ISpriteInstance {},
	Sprite205: class extends self.ISpriteInstance {},
	Sprite206: class extends self.ISpriteInstance {},
	Sprite207: class extends self.ISpriteInstance {},
	Sprite208: class extends self.ISpriteInstance {},
	Sprite209: class extends self.ISpriteInstance {},
	Sprite210: class extends self.ISpriteInstance {},
	Sprite211: class extends self.ISpriteInstance {},
	Sprite212: class extends self.ISpriteInstance {},
	Sprite213: class extends self.ISpriteInstance {},
	Sprite214: class extends self.ISpriteInstance {},
	Sprite215: class extends self.ISpriteInstance {},
	Sprite216: class extends self.ISpriteInstance {},
	Sprite217: class extends self.ISpriteInstance {},
	Sprite218: class extends self.ISpriteInstance {},
	Sprite219: class extends self.ISpriteInstance {},
	Sprite220: class extends self.ISpriteInstance {},
	Sprite221: class extends self.ISpriteInstance {},
	Sprite222: class extends self.ISpriteInstance {},
	Sprite223: class extends self.ISpriteInstance {},
	Sprite224: class extends self.ISpriteInstance {},
	Sprite225: class extends self.ISpriteInstance {},
	Sprite226: class extends self.ISpriteInstance {},
	Sprite227: class extends self.ISpriteInstance {},
	Sprite228: class extends self.ISpriteInstance {},
	freemoney2: class extends self.ISpriteInstance {},
	Sprite229: class extends self.ISpriteInstance {},
	Sprite230: class extends self.ISpriteInstance {},
	moneyhud1: class extends self.ISpriteInstance {},
	moneyhud2: class extends self.ISpriteInstance {},
	fontmoney2: class extends self.ISpriteFontInstance {},
	Sprite231: class extends self.ISpriteInstance {},
	CHECK: class extends self.ISpriteInstance {},
	tipo4: class extends self.ISpriteInstance {},
	tipo5: class extends self.ISpriteInstance {},
	tipo6: class extends self.ISpriteInstance {},
	tipo7: class extends self.ISpriteInstance {},
	arma2: class extends self.ISpriteInstance {},
	Sprite232: class extends self.ISpriteInstance {},
	Sprite233: class extends self.ISpriteInstance {},
	paster: class extends self.ISpriteInstance {},
	Sprite234: class extends self.ISpriteInstance {},
	Sprite235: class extends self.ISpriteInstance {},
	bulletcouns: class extends self.ISpriteFontInstance {},
	lampara: class extends self.ISpriteInstance {},
	Sprite237: class extends self.ISpriteInstance {},
	Sprite238: class extends self.ISpriteInstance {},
	Sprite239: class extends self.ISpriteInstance {},
	Sprite240: class extends self.ISpriteInstance {},
	Sprite236: class extends self.ISpriteInstance {},
	Sprite241: class extends self.ISpriteInstance {},
	Sprite242: class extends self.ISpriteInstance {},
	Sprite243: class extends self.ISpriteInstance {},
	Sprite244: class extends self.ISpriteInstance {},
	arma3: class extends self.ISpriteInstance {},
	grena: class extends self.ISpriteInstance {},
	POWER1: class extends self.ISpriteInstance {},
	POWER2: class extends self.ISpriteInstance {},
	Sprite245: class extends self.ISpriteInstance {},
	Sprite246: class extends self.ISpriteInstance {},
	Sprite247: class extends self.ISpriteInstance {},
	Sprite248: class extends self.ISpriteInstance {},
	Sprite249: class extends self.ISpriteInstance {},
	arma4: class extends self.ISpriteInstance {},
	grena2: class extends self.ISpriteInstance {},
	Bullet3: class extends self.ISpriteInstance {},
	Sprite250: class extends self.ISpriteInstance {},
	Sprite251: class extends self.ISpriteInstance {},
	Sprite252: class extends self.ISpriteInstance {},
	Sprite253: class extends self.ISpriteInstance {},
	guns: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite254: class extends self.ISpriteInstance {},
	Sprite255: class extends self.ISpriteInstance {},
	Sprite256: class extends self.ISpriteInstance {},
	Sprite257: class extends self.ISpriteInstance {},
	Sprite258: class extends self.ISpriteInstance {},
	Sprite259: class extends self.ISpriteInstance {},
	Sprite260: class extends self.ISpriteInstance {},
	Sprite261: class extends self.ISpriteInstance {},
	Sprite262: class extends self.ISpriteInstance {},
	Sprite263: class extends self.ISpriteInstance {},
	Sprite264: class extends self.ISpriteInstance {},
	Sprite265: class extends self.ISpriteInstance {},
	skinbutt: class extends self.ISpriteInstance {},
	gunbutt: class extends self.ISpriteInstance {},
	Sprite268: class extends self.ISpriteInstance {},
	Sprite269: class extends self.ISpriteInstance {},
	Sprite270: class extends self.ISpriteInstance {},
	Sprite271: class extends self.ISpriteInstance {},
	bulletcouns2: class extends self.ISpriteFontInstance {},
	Sprite272: class extends self.ISpriteInstance {},
	guns2: class extends self.ISpriteInstance {},
	cajaiman: class extends self.ISpriteInstance {},
	cajaiman2: class extends self.ISpriteInstance {},
	Sprite273: class extends self.ISpriteInstance {},
	Sprite274: class extends self.ISpriteInstance {},
	Sprite275: class extends self.ISpriteInstance {},
	Sprite276: class extends self.ISpriteInstance {},
	Sprite277: class extends self.ISpriteInstance {},
	Sprite278: class extends self.ISpriteInstance {},
	Sprite279: class extends self.ISpriteInstance {},
	Sprite280: class extends self.ISpriteInstance {},
	Sprite281: class extends self.ISpriteInstance {},
	Sprite282: class extends self.ISpriteInstance {},
	Sprite283: class extends self.ISpriteInstance {},
	Sprite284: class extends self.ISpriteInstance {},
	Sprite285: class extends self.ISpriteInstance {},
	Sprite286: class extends self.ISpriteInstance {},
	Sprite287: class extends self.ISpriteInstance {},
	bulletcouns3: class extends self.ISpriteFontInstance {},
	Sprite288: class extends self.ISpriteInstance {},
	selector2: class extends self.ISpriteInstance {},
	selector3: class extends self.ISpriteInstance {},
	guns3: class extends self.ISpriteInstance {},
	Sprite289: class extends self.ISpriteInstance {},
	TIMECOUNT: class extends self.ISpriteFontInstance {},
	enemgo7: class extends self.ISpriteInstance {},
	enemgo8: class extends self.ISpriteInstance {},
	Sprite290: class extends self.ISpriteInstance {},
	laser2: class extends self.ISpriteInstance {},
	brazo2: class extends self.ISpriteInstance {},
	fonder3: class extends self.ISpriteInstance {},
	Sprite267: class extends self.ISpriteInstance {},
	Sprite292: class extends self.ISpriteInstance {},
	Sprite293: class extends self.ISpriteInstance {},
	Sprite294: class extends self.ISpriteInstance {},
	Sprite295: class extends self.ISpriteInstance {},
	Sprite296: class extends self.ISpriteInstance {},
	Sprite297: class extends self.ISpriteInstance {},
	Sprite298: class extends self.ISpriteInstance {},
	Sprite299: class extends self.ISpriteInstance {},
	Sprite300: class extends self.ISpriteInstance {},
	Sprite301: class extends self.ISpriteInstance {},
	Sprite302: class extends self.ISpriteInstance {},
	Sprite303: class extends self.ISpriteInstance {},
	Sprite304: class extends self.ISpriteInstance {},
	Sprite305: class extends self.ISpriteInstance {},
	Sprite306: class extends self.ISpriteInstance {},
	Sprite307: class extends self.ISpriteInstance {},
	Sprite308: class extends self.ISpriteInstance {},
	Sprite309: class extends self.ISpriteInstance {},
	Sprite310: class extends self.ISpriteInstance {},
	Sprite311: class extends self.ISpriteInstance {},
	Sprite312: class extends self.ISpriteInstance {},
	Sprite313: class extends self.ISpriteInstance {},
	Particles19: class extends self.IParticlesInstance {},
	bulletcouns4: class extends self.ISpriteFontInstance {},
	bulletcouns5: class extends self.ISpriteFontInstance {},
	Sprite314: class extends self.ISpriteInstance {},
	Sprite315: class extends self.ISpriteInstance {},
	Sprite316: class extends self.ISpriteInstance {},
	Sprite317: class extends self.ISpriteInstance {},
	Sprite318: class extends self.ISpriteInstance {},
	Sprite319: class extends self.ISpriteInstance {},
	Sprite320: class extends self.ISpriteInstance {},
	persona: class extends self.ISpriteInstance {},
	e7: class extends self.ISpriteInstance {},
	Sprite321: class extends self.ISpriteInstance {},
	Sprite322: class extends self.ISpriteInstance {},
	Sprite323: class extends self.ISpriteInstance {},
	Sprite324: class extends self.ISpriteInstance {},
	Sprite325: class extends self.ISpriteInstance {},
	Sprite326: class extends self.ISpriteInstance {},
	Sprite327: class extends self.ISpriteInstance {},
	Sprite328: class extends self.ISpriteInstance {},
	Sprite329: class extends self.ISpriteInstance {},
	Sprite330: class extends self.ISpriteInstance {},
	Sprite331: class extends self.ISpriteInstance {},
	Sprite332: class extends self.ISpriteInstance {},
	Sprite333: class extends self.ISpriteInstance {},
	Sprite334: class extends self.ISpriteInstance {},
	LiveFont8: class extends self.ISpriteFontInstance {},
	Sprite335: class extends self.ISpriteInstance {},
	Sprite336: class extends self.ISpriteInstance {},
	Sprite337: class extends self.ISpriteInstance {},
	Sprite338: class extends self.ISpriteInstance {},
	Sprite339: class extends self.ISpriteInstance {},
	Sprite340: class extends self.ISpriteInstance {},
	Sprite341: class extends self.ISpriteInstance {},
	Sprite342: class extends self.ISpriteInstance {},
	Sprite343: class extends self.ISpriteInstance {},
	s21: class extends self.ISpriteInstance {},
	s22: class extends self.ISpriteInstance {},
	s23: class extends self.ISpriteInstance {},
	s24: class extends self.ISpriteInstance {},
	Sprite344: class extends self.ISpriteInstance {},
	Sprite345: class extends self.ISpriteInstance {},
	Sprite346: class extends self.ISpriteInstance {},
	Sprite347: class extends self.ISpriteInstance {},
	Sprite348: class extends self.ISpriteInstance {},
	Sprite349: class extends self.ISpriteInstance {},
	s25: class extends self.ISpriteInstance {},
	s26: class extends self.ISpriteInstance {},
	s27: class extends self.ISpriteInstance {},
	s28: class extends self.ISpriteInstance {},
	s29: class extends self.ISpriteInstance {},
	s30: class extends self.ISpriteInstance {},
	Sprite350: class extends self.ISpriteInstance {},
	Sprite351: class extends self.ISpriteInstance {},
	Sprite352: class extends self.ISpriteInstance {},
	Sprite353: class extends self.ISpriteInstance {},
	Sprite354: class extends self.ISpriteInstance {},
	Sprite355: class extends self.ISpriteInstance {},
	Sprite356: class extends self.ISpriteInstance {},
	Sprite357: class extends self.ISpriteInstance {},
	Sprite358: class extends self.ISpriteInstance {},
	Sprite359: class extends self.ISpriteInstance {},
	Sprite360: class extends self.ISpriteInstance {},
	Sprite361: class extends self.ISpriteInstance {},
	Sprite362: class extends self.ISpriteInstance {},
	Sprite363: class extends self.ISpriteInstance {},
	Sprite364: class extends self.ISpriteInstance {},
	Sprite365: class extends self.ISpriteInstance {},
	Sprite366: class extends self.ISpriteInstance {},
	Sprite367: class extends self.ISpriteInstance {},
	Sprite368: class extends self.ISpriteInstance {},
	Sprite369: class extends self.ISpriteInstance {},
	Sprite370: class extends self.ISpriteInstance {},
	Sprite371: class extends self.ISpriteInstance {},
	Sprite372: class extends self.ISpriteInstance {},
	Sprite373: class extends self.ISpriteInstance {},
	Sprite374: class extends self.ISpriteInstance {},
	Sprite375: class extends self.ISpriteInstance {},
	Sprite376: class extends self.ISpriteInstance {},
	Sprite377: class extends self.ISpriteInstance {},
	flame1: class extends self.ISpriteInstance {},
	Sprite378: class extends self.ISpriteInstance {},
	Sprite379: class extends self.ISpriteInstance {},
	Sprite380: class extends self.ISpriteInstance {},
	Sprite381: class extends self.ISpriteInstance {},
	bulletcouns6: class extends self.ISpriteFontInstance {},
	Sprite382: class extends self.ISpriteInstance {},
	ac5: class extends self.ISpriteInstance {},
	ac2: class extends self.ISpriteInstance {},
	ac3: class extends self.ISpriteInstance {},
	ac4: class extends self.ISpriteInstance {},
	ac6: class extends self.ISpriteInstance {},
	ac1: class extends self.ISpriteInstance {},
	flasher: class extends self.ISpriteInstance {},
	Woods: class extends self.ISpriteInstance {},
	Sprite383: class extends self.ISpriteInstance {},
	Sprite384: class extends self.ISpriteInstance {},
	Sprite385: class extends self.ISpriteInstance {},
	brazo3: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Family4: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {},
	Family2: class extends self.ISpriteInstance {},
	Family3: class extends self.ISpriteInstance {},
	bulletcajas: class extends self.ISpriteInstance {}
}